version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
   
  rabbitmq:
    image: rabbitmq:3.9.15-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
    restart: unless-stopped
  
  backend:
    image: alitawfiq/quant-task
    container_name: backend
### Remove the comments below if you want to test the build(You can pull the image diectly from docker hub without building) ###
#    build: 
#      context: ./
#      dockerfile: Dockerfile

    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8080:8080
    links:
      - mongodb
      - rabbitmq
    restart: unless-stopped
